### ISSUE TITLE
Document body overflows device window

### ISSUE THREAD

**Issue by othyn** [coronafriend/coronafriend-site#11]
I've experienced this issue a lot whilst developing sites, where usually a `container` element has a pad or margin on it that causes the document to overflow the device window when the document width is compressed to the mobile form.

See in this example the overflow within Safari:

![Example in Safari](https://media.giphy.com/media/fSBBE0FZIdN2jzOdOh/giphy.gif)

Then on firefox (again I've experienced this before), it is experiencing the overflow to the same as Safari, but also at the bottom. This is due to some quirks of implementations of pad/margin vs that of WebKit.

![Example of the overflow in Firefox](https://media.giphy.com/media/j32NmJLYoQs5MJoBTw/giphy.gif)

The dark mode could also do with some looking at for colours.

**Comment by vicchi** [comment]
Related to #6

**Comment by othyn** [comment]
Just tried it on desktop in development too, its doing it on any screen size:

![Example desktop](https://media.giphy.com/media/d8R9MlcdBQ3KrNnkQy/giphy.gif)

And its caused by the footer row being outside of a container.

**Comment by vicchi** [comment]
@othyn (face palm) ... will you fix this?

**Comment by othyn** [comment]
Yep, currently working on a fix. Although proving a little more difficult as the `container` element places a safe padding around the element causing it not to fit to the page 🤦‍♂ 

CSS, DNS and printers are the bane of the tech world!

**Comment by othyn** [comment]
Within bootstrap, a little known rule is that you have to contain any `row` elements within a `container` element so that the row is placed correctly. 🤦‍♂
