### ISSUE TITLE
Adjust map container size and margins on mobile resolutions

### ISSUE THREAD

**Issue by vicchi** [coronafriend/coronafriend-site#6]
> The map takes up my whole screen on mobile, which is an issue when scrolling down (as the map scroll takes over if you scroll on it) and also makes the information after you tap a road under it invisible, which will make it hard to navigate / discover, so hard to claim a road.  I’d make it half the size of the screen.  Also, we should think about how to make it really clear how to claim a road - maybe put the form part appear above the map, or auto-scroll if possible?

**Comment by othyn** [comment]
Here is an example of the problem at hand, using Firefox's Responsive Design Mode and emulating an iPhone 6 running iOS 11 to demonstrate a 'worse case' scenario.

![Screen Shot 2020-04-02 at 13 21 46](https://user-images.githubusercontent.com/7256684/78248815-3c867900-74e5-11ea-8464-d4c8d5aae1c8.png)
